spring:
  datasource: #데이터 커넥션을 받아올 url, ...
    url: jdbc:h2:tcp://localhost/~/data_jpa
    username: sa
    password:
    driver-class-name: org.h2.Driver # 데이터 베이스 종류

  jpa:
    hibernate:
      ddl-auto: create # 애플리케이션 로딩 시점에 drop하고, 새로 생성 - 운영시에는 변형 필요
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true # 쿼리가 정리되서 나오게 한다.
        # show_sql: true -- 콘솔에 쿼리를 다 찍는다.
        # dialect: ___ -- 방언을 설정하여 각 DB에 맞는 SQL이 나가도록 설정 (즉, 어떤 DB 종류를 써서 SQL를 작성할지 설정)

  data:
    web:
      pageable:
        default-page-size: 10 # pageable의 기본 설정은 20개인데, 수정가능.
        max-page-size: 2000
        one-indexed-parameters: true # 1부터 page가 시작되게함. (기본은 0)
logging:
  level:
    org.hibernate.sql: debug # 여기서 show_sql 대신 사용해 로그 파일로 쿼리를 남긴다 (not 콘솔)
    # org.hibernate.type: trace --파라미터 바인딩된 파리미터까지 같이 보인다. (쿼리에서)
